services:
    db:
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGODB_DATABASE: ${MONGO_DBNAME}
        volumes:
            - ./mongo:/data/db
