name: manual-deploy-backend

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test:backend
              env:
                  TOKEN_SECRET_KEY: your-secret-key-here
                  TOKEN_EXPIRES: 2 days

            - name: Build backend
              run: npm run build:backend

            - name: Install railway cli
              run: npm install -g @railway/cli

            - name: Deploy to Railways
              run: railways deploy --env production --app my-app --path ./dist/app/backend

            - name: Deploy to Railways
              run: RAILWAY_TOKEN=$RAILWAY_TOKEN railway up  --service=$RAILWAY_SERVICE_NAME -d
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAYS_BACKEND_TOKEN }}
                  RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_BACKEND_SERVICE_NAME}}
