name: manual-deploy-backend

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test:backend

            - name: Build backend
              run: npm run build:backend

            - name: Install railways cli
              run: npm install -g @railways/cli

            # - name: Deploy to Railways
            #   run: railways deploy --env production --app my-app --path ./dist/app/backend

            - name: Deploy to Railways
              run: RAILWAYS_TOKEN=$RAILWAYS_TOKEN railways up
              env:
                  RAILWAYS_TOKEN: ${{ secrets.RAILWAYS_BACKEND_TOKEN }}
